name: Follow-up Workflow

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]

jobs:
  follow-up-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Perform follow-up actions
      run: echo "CI workflow has completed on master branch"
