name: Code Coverage
run-name: 🚩Code Coverage + slack notification

on:
  push:
    branches:
      - main

jobs:
  # build
  failing-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x,21.x,22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test -- --coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  # notification on success    
  on-success:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.failing-job.result == 'success') }}
    needs:
      - failing-job
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C073DKR20GL'
          payload: |
            {
              "text": "💯🎉 test-Code Coverage succeeded: ${{ github.run_id }}\n${{ github.run_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "💯🎉 test-Code Coverage succeeded: ${{ github.run_id }}\n${{ github.run_url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
  # notification on failure
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.failing-job.result == 'failure' || needs.failing-job.result == 'timed_out') }}
    needs:
      - failing-job
    steps:
    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: 'C073DKR20GL'
        payload: |
          {
            "text": "⛔ test-Code Coverage failed: ${{ github.run_id }}\n${{ github.run_url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "⛔ test-Code Coverage failed: ${{ github.run_id }}\n${{ github.run_url }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

